import { defineConfig } from 'vite';
import { resolve } from 'path';
import dts from 'vite-plugin-dts';

export default defineConfig({
  plugins: [
    dts({
      tsconfigPath: './tsconfig.json',
      rollupTypes: false,
    }),
  ],
  build: {
    lib: {
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        'components/button/index': resolve(__dirname, 'src/components/button/index.ts'),
        'components/text-field/index': resolve(__dirname, 'src/components/text-field/index.ts'),
        'components/checkbox/index': resolve(__dirname, 'src/components/checkbox/index.ts'),
        'components/radio/index': resolve(__dirname, 'src/components/radio/index.ts'),
        'components/switch/index': resolve(__dirname, 'src/components/switch/index.ts'),
        'components/select/index': resolve(__dirname, 'src/components/select/index.ts'),
        'components/card/index': resolve(__dirname, 'src/components/card/index.ts'),
        'components/dialog/index': resolve(__dirname, 'src/components/dialog/index.ts'),
        'components/snackbar/index': resolve(__dirname, 'src/components/snackbar/index.ts'),
        'components/icon/index': resolve(__dirname, 'src/components/icon/index.ts'),
        'components/icon-button/index': resolve(__dirname, 'src/components/icon-button/index.ts'),
        'components/fab/index': resolve(__dirname, 'src/components/fab/index.ts'),
        'components/chips/index': resolve(__dirname, 'src/components/chips/index.ts'),
        'components/menu/index': resolve(__dirname, 'src/components/menu/index.ts'),
        'components/tabs/index': resolve(__dirname, 'src/components/tabs/index.ts'),
        'components/progress/index': resolve(__dirname, 'src/components/progress/index.ts'),
        'components/list/index': resolve(__dirname, 'src/components/list/index.ts'),
        'components/slider/index': resolve(__dirname, 'src/components/slider/index.ts'),
        'components/divider/index': resolve(__dirname, 'src/components/divider/index.ts'),
        'components/ripple/index': resolve(__dirname, 'src/components/ripple/index.ts'),
        'components/elevation/index': resolve(__dirname, 'src/components/elevation/index.ts'),
        'components/focus-ring/index': resolve(__dirname, 'src/components/focus-ring/index.ts'),
        'components/badge/index': resolve(__dirname, 'src/components/badge/index.ts'),
        'components/segmented-button/index': resolve(__dirname, 'src/components/segmented-button/index.ts'),
        'components/navigation-bar/index': resolve(__dirname, 'src/components/navigation-bar/index.ts'),
        'components/tooltip/index': resolve(__dirname, 'src/components/tooltip/index.ts'),
        'components/top-app-bar/index': resolve(__dirname, 'src/components/top-app-bar/index.ts'),
        'components/bottom-app-bar/index': resolve(__dirname, 'src/components/bottom-app-bar/index.ts'),
        'components/navigation-rail/index': resolve(__dirname, 'src/components/navigation-rail/index.ts'),
        'components/search-bar/index': resolve(__dirname, 'src/components/search-bar/index.ts'),
        'components/navigation-drawer/index': resolve(__dirname, 'src/components/navigation-drawer/index.ts'),
        'components/bottom-sheet/index': resolve(__dirname, 'src/components/bottom-sheet/index.ts'),
        'components/date-picker/index': resolve(__dirname, 'src/components/date-picker/index.ts'),
        'components/time-picker/index': resolve(__dirname, 'src/components/time-picker/index.ts'),
        'components/carousel/index': resolve(__dirname, 'src/components/carousel/index.ts'),
        'components/side-sheet/index': resolve(__dirname, 'src/components/side-sheet/index.ts'),
        'components/accordion/index': resolve(__dirname, 'src/components/accordion/index.ts'),
        'components/data-table/index': resolve(__dirname, 'src/components/data-table/index.ts'),
        'components/autocomplete/index': resolve(__dirname, 'src/components/autocomplete/index.ts'),
        'components/stepper/index': resolve(__dirname, 'src/components/stepper/index.ts'),
        'components/skeleton/index': resolve(__dirname, 'src/components/skeleton/index.ts'),
        'components/popover/index': resolve(__dirname, 'src/components/popover/index.ts'),
        'components/rating/index': resolve(__dirname, 'src/components/rating/index.ts'),
        'components/timeline/index': resolve(__dirname, 'src/components/timeline/index.ts'),
        'components/avatar/index': resolve(__dirname, 'src/components/avatar/index.ts'),
        'components/breadcrumbs/index': resolve(__dirname, 'src/components/breadcrumbs/index.ts'),
        'components/alert/index': resolve(__dirname, 'src/components/alert/index.ts'),
        'components/file-upload/index': resolve(__dirname, 'src/components/file-upload/index.ts'),
        'components/pagination/index': resolve(__dirname, 'src/components/pagination/index.ts'),
        'components/chip-input/index': resolve(__dirname, 'src/components/chip-input/index.ts'),
        'components/speed-dial/index': resolve(__dirname, 'src/components/speed-dial/index.ts'),
        'components/swipe-actions/index': resolve(__dirname, 'src/components/swipe-actions/index.ts'),
        'components/pull-to-refresh/index': resolve(__dirname, 'src/components/pull-to-refresh/index.ts'),
        'components/tree-view/index': resolve(__dirname, 'src/components/tree-view/index.ts'),
        'components/image-list/index': resolve(__dirname, 'src/components/image-list/index.ts'),
        'components/virtual-list/index': resolve(__dirname, 'src/components/virtual-list/index.ts'),
        'components/color-picker/index': resolve(__dirname, 'src/components/color-picker/index.ts'),
        'components/date-range-picker/index': resolve(__dirname, 'src/components/date-range-picker/index.ts'),
        'components/multi-select/index': resolve(__dirname, 'src/components/multi-select/index.ts'),
        'components/parallax-header/index': resolve(__dirname, 'src/components/parallax-header/index.ts'),
        'components/button-group/index': resolve(__dirname, 'src/components/button-group/index.ts'),
        'components/split-button/index': resolve(__dirname, 'src/components/split-button/index.ts'),
        'components/floating-toolbar/index': resolve(__dirname, 'src/components/floating-toolbar/index.ts'),
        'components/loading-indicator/index': resolve(__dirname, 'src/components/loading-indicator/index.ts'),
        'theme/index': resolve(__dirname, 'src/theme/index.ts'),
      },
      formats: ['es', 'cjs'],
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'react/jsx-runtime'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
        },
      },
    },
    sourcemap: true,
    minify: false,
    copyPublicDir: false,
  },
});
